title: jjk7_blog
author: James Keane
email: contact@jjk7.com
description: >-
  A blog about software development, cloud & web engineering from someone who
  knows some stuff about it. Might also delve into other topics that I find
  interesting including: maths, parenting, ping pong, VR, LLMs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jjk7.com"
twitter_username: jamesjkeane
github_username:  jameskeane
linkedin_username: therealjameskeane

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Delete exif data by: exiftool -overwrite_original -all= assets/**/*.jpg